### DISCUSSION TITLE
Unable to Start Infinispan with a Managed Datasource

### DISCUSSION THREAD

**Discussion by stevejr** [infinispan/infinispan#10490] [Q&A] [answered]
I am trying to declare a managed datasource in my Infinispan.yaml configuration file and am hitting 2 issues. My goal is to use an external Infinispan cluster with Keycloak.

1. If I declare the datasource without the connectionPool field Infinispan fails to start with the below error:

```
2022-11-29 18:06:10,123 FATAL (main) [org.infinispan.SERVER] ISPN080028: Infinispan Server failed to start java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.infinispan.commons.configuration.attributes.Attribute.get()" is null
	at org.infinispan.server.configuration.DataSourceConfiguration.maxSize(DataSourceConfiguration.java:94)
	at org.infinispan.server.datasource.DataSourceFactory.create(DataSourceFactory.java:46)
	at org.infinispan.server.Server.run(Server.java:402)
	at org.infinispan.server.Bootstrap.runInternal(Bootstrap.java:173)
	at org.infinispan.server.tool.Main.run(Main.java:98)
	at org.infinispan.server.Bootstrap.main(Bootstrap.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.infinispan.server.loader.Loader.run(Loader.java:106)
	at org.infinispan.server.loader.Loader.main(Loader.java:51)
```

2. If I add the connectionPool field to the datasource I get an error stating that `connection-pool` is not a valid element.

I am running Infinispan in a Kubernetes cluster and am using the image docker.io/infinispan/server:14.0.

My Infinispan.yaml file contains the following:

```
  infinispan:
    cacheContainer:
      name: default
      # If security is enabled then we need to authenticate from Keycloak to Infinispan. 
      # If security is disabled we don't need to authenticate but lose access to the Console unless we configure a more fine grained policy
      # See https://infinispan.org/docs/stable/titles/server/server.html#creating-custom-roles-statically_rbac-remote - Section 8.5
      security: null # Set to null to override the default values.yaml value
        # authorization: {}
      transport:
        cluster: ${infinispan.cluster.name:cluster}
        node-name: ${infinispan.node.name:}
        stack: kubernetes
      caches:
        authenticationSessions:
          distributedCache:
            # To use a DB as a backing datasource we will need to install the driver so we basically need to maintain our own Infinispan image!
            # See https://infinispan.org/docs/stable/titles/configuring/configuring.html#configuring-server-datasources_persistence, Section 6.9.1
            # persistence:
            #   passivation: false
            #   stringKeyedJdbcStore:
            #     dataSource:
            #       jndi-url: "jdbc/postgres"
            #     preload: false
            #     shared: true
            #     stringKeyedTable:
            #       prefix: "ispn"
            #       dropOnExit: false
            #       createOnStart: true
            #       idColumn:
            #         name: "ID"
            #         type: "VARCHAR(255)"
            #       dataColumn:
            #         name: "DATUM"
            #         type: "BYTEA"
            #       timestampColumn:
            #         name: "VERSION"
            #         type: "BIGINT"
            #       segmentColumn:
            #         name: "S"
            #         type: "INT"
            owners: "${env.CACHE_OWNERS_AUTH_SESSIONS_COUNT:2}"
        clientSessions:
          distributedCache:
            owners: "${env.CACHE_OWNERS_COUNT:2}"
        offlineSessions:
          distributedCache:
            owners: "${env.CACHE_OWNERS_COUNT:2}"
        sessions:
          distributedCache:
            owners: "${env.CACHE_OWNERS_COUNT:2}"
        offlineClientSessions:
          distributedCache:
            owners: "${env.CACHE_OWNERS_COUNT:2}"
        loginFailures:
          distributedCache:
            owners: "${env.CACHE_OWNERS_COUNT:2}"
        actionTokens:
          distributedCache:
            owners: "${env.CACHE_OWNERS_COUNT:2}"
        work:
          replicatedCache: {}
    server:
      # To use a DB as a backing datasource we will need to install the driver so we basically need to maintain our own Infinispan image!
      # See https://infinispan.org/docs/stable/titles/configuring/configuring.html#configuring-server-datasources_persistence, Section 6.9.1
      dataSources:
      - name: "ds"
        jndiName: "jdbc/postgres"
        statistics: true
        connectionFactory:
          driver: "org.postgresql.Driver"
          url: "jdbc:postgresql://${env.DB_ADDR}:${env.DB_PORT:5432}/${env.DB_DATABASE:keycloak}${env.JDBC_PARAMS_IS:}"
          username: "${env.DB_USER}"
          password: "${env.DB_PASSWORD}"
          connectionProperties:
            name: value
          newConnectionSql: "SELECT 1"
          transactionIsolation: "READ_COMMITTED"
      #   connectionPool:
      #     initialSize: 1
      #     maxSize: 10
      #     minSize: 3
      #     backgroundValidation: 1000
      #     idleRemoval: 1
      #     blockingTimeout: 1000
      #     leakDetection: 10000
      endpoints:
      - connectors:
          hotrod:
            hotrodConnector: null
          rest:
            restConnector: null
        # Disable the securityRealm so that we do not apply any policies to this connection. This is needed so that we can connect from Keycloak to Infinispan.
        # If this is on then we have to have security on in the cacheContainer above
        # securityRealm: default
        socketBinding: default
      - connectors:
          rest:
            # set this to null to remove the authentication 
            restConnector: null
              # authentication:
              #   mechanisms: BASIC
        # Disable the securityRealm so that we do not apply any policies to this connection. This is needed so that we can connect from Keycloak to Infinispan.
        # If this is on then we have to have security on in the cacheContainer above
        # securityRealm: metrics
        socketBinding: metrics
      interfaces:
      - inetAddress:
          value: ${infinispan.bind.address:127.0.0.1}
        name: public
      security:
        credentialStores:
        - clearTextCredential:
            clearText: secret
          name: credentials
          path: credentials.pfx
        securityRealms:
        - name: default
          propertiesRealm:
            groupProperties:
              path: groups.properties
              # what does this actually do?
              relativeTo: infinispan.server.config.path
            groupsAttribute: Roles
            userProperties:
              path: users.properties
              # what does this actually do?
              relativeTo: infinispan.server.config.path
              plainText: true
        - name: metrics
          propertiesRealm:
            groupProperties:
              path: metrics-groups.properties
              relativeTo: infinispan.server.config.path
            groupsAttribute: Roles
            userProperties:
              path: metrics-users.properties
              relativeTo: infinispan.server.config.path
      socketBindings:
        defaultInterface: public
        portOffset: ${infinispan.socket.binding.port-offset:0}
        socketBinding:
        - name: default
          port: 11222
        - name: metrics
          port: 11223
```

I have installed the Postgres JDBC driver in the Infinispan image and see that it is loaded on the startup:

```
(main) [org.infinispan.SERVER] ISPN080027: Loaded extension 'org.postgresql.Driver'
```

**Comment by stevejr** [comment]
Hi @tristantarrant - sorry for the shout out but any chance you could comment on the above for me? Been trying to resolve this issue for a couple of days. Thanks.

**Reply by tristantarrant** [reply]
I have created https://issues.redhat.com/browse/ISPN-14356

**Reply by tristantarrant** [reply]
As for the `connectionPool` element, I tried it and it works:

```yaml
server:
    dataSources:
    - name: "ds"
      jndiName: "jdbc/postgres"
      statistics: true
      connectionFactory:
        driver: "org.postgresql.Driver"
        url: "jdbc:postgresql://${env.DB_ADDR}:${env.DB_PORT:5432}/${env.DB_DATABASE:keycloak}${env.JDBC_PARAMS_IS:}"
        username: "${env.DB_USER}"
        password: "${env.DB_PASSWORD}"
        connectionProperties:
          name: value
        newConnectionSql: "SELECT 1"
        transactionIsolation: "READ_COMMITTED"
      connectionPool:
        initialSize: 1
        maxSize: 10
        minSize: 3
        backgroundValidation: 1000
        idleRemoval: 1
        blockingTimeout: 1000
        leakDetection: 10000
```

**Reply by stevejr** [reply]
Hi @tristantarrant, thanks for raising the bug.

I still cannot get the connection-pool to work. Are you using the Helm chart and Kubenertes for your deployment? Also, what version of Infinispan are you using?

Does the Infinispan.yml need to be in a specific order as when I look at what the ConfigMap contains the order of the elements is not the same as above.

**Reply by tristantarrant** [reply]
Ever since https://issues.redhat.com/browse/ISPN-13261 (13.0.0.CR1) order should not matter. I tested this with a bare-metal installation, but the Helm Chart should pass things through as-is. This is the yaml I used (slightly modified from yours): https://gist.github.com/tristantarrant/857252ad3aa486e65825f7331532ea30

**Reply by stevejr** [reply]
It looks pretty identical to mine so cannot for the life of me understand why my one is not working.

Do you store your Infinispan.yml in a ConfigMap and then mount into the pod?

**Reply by stevejr** [reply]
Apart from setting `security: null` to make sure the default values.yaml does not get applied for that field my Infinispan.yml is identical to yours and does not work with the latest Infinispan Helm Chart

**Reply by stevejr** [reply]
Other information:

Kubernetes Cluster: Minikube, K8s version 1.22.12
Postgres JDBC Driver version: postgresql-42.5.1.jar
Infinispan Helm Chart Version: 0.3.0

The Helm chart has been downloaded and customised to allow for additional environment variables to be passed into the Statefulset.

**Comment by stevejr** [comment, marked as answer]
@tristantarrant - I have tested again and there is definitely an issue with the field order. I copied in my Infinispan.yml as it appears in my helm values.yaml i.e what I posted originally and I can confirm the Infinispan server starts.

When the Infinispan.yml that is mounted from the ConfigMap is used the server does not start. I believe that the server parser is expecting the name and jndiName attributes as the first 2 in the list.

**Reply by tristantarrant** [reply]
I just tried reordering the elements on a local server, and it started fine
```yaml
dataSources:
    - statistics: true
      connectionFactory:
        driver: "org.postgresql.Driver"
        url: "jdbc:postgresql://${env.DB_ADDR}:${env.DB_PORT:5432}/${env.DB_DATABASE:keycloak}${env.JDBC_PARAMS_IS:}"
        username: "${env.DB_USER}"
        password: "${env.DB_PASSWORD}"
        connectionProperties:
          name: value
        newConnectionSql: "SELECT 1"
        transactionIsolation: "READ_COMMITTED"
      connectionPool:
        initialSize: 1
        maxSize: 10
        minSize: 3
        backgroundValidation: 1000
        idleRemoval: 1
        blockingTimeout: 1000
        leakDetection: 10000
      jndiName: "jdbc/postgres"
      name: "ds"
```

**Reply by tristantarrant** [reply]
Which version are you using ? 14.0.2.Final ?

**Reply by stevejr** [reply]
I am using the image tag 14 from Docker Hub - tried the one on quay.io aswell with the same result.

Are you able to deploy the server using the Helm Chart?

**Reply by stevejr** [reply]
Only other thing I can think of is that the ConfigMap is mounted as a read only filesystem - does that matter?

When I baked the Infinispan.yml into the image I put it onto the /opt directory which is R/W.

**Reply by ryanemerson** [reply]
The helm chart is re-ordering the server configuration which I believe is causing an issue:

The ConfigMap config is:

```yaml
    infinispan:
      cacheContainer:
        caches:
          actionTokens:
            distributedCache:
              owners: ${env.CACHE_OWNERS_COUNT:2}
          authenticationSessions:
            distributedCache:
              owners: ${env.CACHE_OWNERS_AUTH_SESSIONS_COUNT:2}
          clientSessions:
            distributedCache:
              owners: ${env.CACHE_OWNERS_COUNT:2}
          loginFailures:
            distributedCache:
              owners: ${env.CACHE_OWNERS_COUNT:2}
          offlineClientSessions:
            distributedCache:
              owners: ${env.CACHE_OWNERS_COUNT:2}
          offlineSessions:
            distributedCache:
              owners: ${env.CACHE_OWNERS_COUNT:2}
          sessions:
            distributedCache:
              owners: ${env.CACHE_OWNERS_COUNT:2}
          work:
            replicatedCache: {}
        name: default
        security: null
        transport:
          cluster: ${infinispan.cluster.name:cluster}
          node-name: ${infinispan.node.name:}
          stack: kubernetes
      server:
        dataSources:
        - connectionFactory:
            connectionProperties:
              name: value
            driver: org.postgresql.Driver
            newConnectionSql: SELECT 1
            password: ${env.DB_PASSWORD:password}
            transactionIsolation: READ_COMMITTED
            url: jdbc:postgresql://127.0.0.1:${env.DB_PORT:5432}/${env.DB_DATABASE:keycloak}${env.JDBC_PARAMS_IS:}
            username: ${env.DB_USER:admin}
          connectionPool:
            backgroundValidation: 1000
            blockingTimeout: 1000
            idleRemoval: 1
            initialSize: 1
            leakDetection: 10000
            maxSize: 10
            minSize: 3
          jndiName: jdbc/postgres
          name: ds
          statistics: true
        endpoints:
        - connectors:
            hotrod:
              hotrodConnector: null
            rest:
              restConnector: null
          socketBinding: default
        - connectors:
            rest:
              restConnector: null
          socketBinding: metrics
        interfaces:
        - inetAddress:
            value: ${infinispan.bind.address:127.0.0.1}
          name: public
        security:
          credentialStores:
          - clearTextCredential:
              clearText: secret
            name: credentials
            path: credentials.pfx
          securityRealms:
          - name: default
            propertiesRealm:
              groupProperties:
                path: groups.properties
                relativeTo: infinispan.server.config.path
              groupsAttribute: Roles
              userProperties:
                path: users.properties
                plainText: true
                relativeTo: infinispan.server.config.path
          - name: metrics
            propertiesRealm:
              groupProperties:
                path: metrics-groups.properties
                relativeTo: infinispan.server.config.path
              groupsAttribute: Roles
              userProperties:
                path: metrics-users.properties
                relativeTo: infinispan.server.config.path
        socketBindings:
          defaultInterface: public
          portOffset: ${infinispan.socket.binding.port-offset:0}
          socketBinding:
          - name: default
            port: 11222
          - name: metrics
            port: 11223
```

Which results in:

```java
java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.infinispan.server.loader.Loader.run(Loader.java:106)
    at org.infinispan.server.loader.Loader.main(Loader.java:51)
Caused by: org.infinispan.commons.configuration.io.ConfigurationReaderException: Unexpected element 'connection-pool' encountered[103,1]
    at org.infinispan.configuration.parsing.ParseUtils.unexpectedElement(ParseUtils.java:36)
    at org.infinispan.server.configuration.ServerConfigurationParser.parseDataSources(ServerConfigurationParser.java:1288)
    at org.infinispan.server.configuration.ServerConfigurationParser.parseServerElements(ServerConfigurationParser.java:127)
    at org.infinispan.server.configuration.ServerConfigurationParser.readElement(ServerConfigurationParser.java:104)
    at org.infinispan.configuration.parsing.ParserRegistry.parseElement(ParserRegistry.java:209)
    at org.infinispan.configuration.parsing.ConfigurationBuilderHolder.handleAnyElement(ConfigurationBuilderHolder.java:139)
    at org.infinispan.commons.configuration.io.AbstractConfigurationReader.handleAny(AbstractConfigurationReader.java:57)
    at org.infinispan.configuration.parsing.Parser.readElement(Parser.java:99)
    at org.infinispan.configuration.parsing.ParserRegistry.parseElement(ParserRegistry.java:209)
    at org.infinispan.configuration.parsing.ParserRegistry.parse(ParserRegistry.java:187)
    at org.infinispan.configuration.parsing.ParserRegistry.parse(ParserRegistry.java:175)
    at org.infinispan.configuration.parsing.ParserRegistry.parse(ParserRegistry.java:169)
    at org.infinispan.server.Server.parseConfiguration(Server.java:319)
    at org.infinispan.server.Server.<init>(Server.java:234)
    at org.infinispan.server.Bootstrap.runInternal(Bootstrap.java:171)
    at org.infinispan.server.tool.Main.run(Main.java:98)
    at org.infinispan.server.Bootstrap.main(Bootstrap.java:56)
    ... 6 more
```

A fix on the Infinispan server is required.

@stevejr As an aside, I have created a PR that will make it so that you can specify Infinispan server dependencies via the values.yaml

https://github.com/infinispan/infinispan-helm-charts/pull/56
