### DISCUSSION TITLE
Infinispan cluster behind reverse proxy

### DISCUSSION THREAD

**Discussion by antonionappi88** [infinispan/infinispan#10493] [Q&A]
Hello,
I have an infinispan two nodes cluster. They are connected using TCPPING and static list. 
I added in front an haproxy as reverse proxy but here i have problems. When I try to connect to the cluster using HAProxy address it doesn't work. Only if one of the node is down then it works, while if they are both up I get:

```bash
Could not connect to server: java.net.ProtocolException: Too many follow-up requests: 21
```
Do you have any clue how put a proxy in front of a infinispan cluster ?

**Comment by tristantarrant** [comment]
You need to disable client intelligence by setting it to BASIC: https://infinispan.org/docs/stable/titles/hotrod_java/hotrod_java.html#hotrod-client-intelligence_hotrod-java-client

**Comment by antonionappi88** [comment]
Hello @tristantarrant ,
First thanks for the reply!

I still have problems to connect from keycloak to the infinispan behind HAProxy. (Please let me know if you prefer that i open the ticket on Keycloak github).

I setup my haproxy in TCP and also in HTTP mode to both try. I'm testing in two different ways:
- infinispan-cli
- keycloak deployment on K8s (version 20)

When I use HTTP mode
- infinispan-cli: i got the behavior above (not sure how to set up the cli with basic intelligence).
- keycloak: fails with this error:

```java
Caused by: org.infinispan.client.hotrod.exceptions.InvalidResponseException:: ISPN004003: Invalid magic number. Expected 0xa1 and received 0x48
        at org.infinispan.client.hotrod.impl.protocol.Codec20.readMessageId(Codec20.java:146)
        at org.infinispan.client.hotrod.impl.transport.netty.HeaderDecoder.decode(HeaderDecoder.java:85)
        at org.infinispan.client.hotrod.impl.transport.netty.HintedReplayingDecoder.callDecode(HintedReplayingDecoder.java:94)
        ... 20 more
```


When I use the TCP mode
- infinispan-cli: it works!
- keycloak fails with this error:

```bash
2022-11-30 10:53:51,897 WARN  [org.infinispan.HOTROD] (Thread-0) ISPN004005: Error received from the server: java.lang.IllegalArgumentException: No interface address matching '/ISPN_IP_NODE_1' in MultiHomedServerAddress{port=11333, addresses=[/ISPN_IP_NODE_2/21, /127.0.0.1/8]}
```

I tried as you suggested to setup the hotrod client with basic intelligence but didn't help for the keycloak case:

```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  ingress:
    enabled: false
  hostname:
    hostname: my-host.com
  http:
    httpEnabled: true
    httpPort: 8080
  transaction:
    xaEnabled: false
  db:
    passwordSecret:
      key: password
      name: keycloak-db-secret
    usernameSecret:
      key: username
      name:  keycloak-db-secret
    url: jdbc:postgresql://postgres-main.com:6602,postgres-replica.com:6603/keycloak
    vendor: postgres
    schema: keycloak
    poolMaxSize: 300
  unsupported:
    podTemplate:
      metadata:
        labels:
          my-label: "keycloak"
      spec:
        containers:
          - volumeMounts:
              - name: cache-ispn
                mountPath: /opt/keycloak/conf/cache-ispn.xml
                subPath: cache-ispn.xml
              - name: quarkus-properties
                mountPath: /opt/keycloak/conf/quarkus.properties.
                subPath: quarkus.properties
        volumes:
          - name: quarkus-properties
            configMap:
              name: quarkus-properties
          - name: cache-ispn
            configMap:
              name: cache-ispn
  additionalOptions:
  - name: cache-config-file
    value: "cache-ispn.xml"
  - name: log-level
    value: debug
  - name: proxy
    value: edge
```

Where the `quarkus-properties` is just:
```bash
quarkus.infinispan-client.client-intelligence=BASIC
```

and the cache-ispn.xml(removed some duplicate cache configuration for simplicity) is

```xml
<?xml version="1.0" encoding="UTF-8"?>

<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:13.0 http://www.infinispan.org/schemas/infinispan-config-13.0.xsd"
        xmlns="urn:infinispan:config:13.0">

    <cache-container name="keycloak">
        <transport lock-timeout="60000" site="site1"/>
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:13.0"
                          cache="sessions"
                          fetch-state="false"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="my-proxy-hostname" port="80" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="username" password="password" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:13.0"
                          cache="work"
                          fetch-state="false"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="my-proxy-hostname" port="80" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="username" password="password" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </replicated-cache>
    </cache-container>
</infinispan>
```

Since i'm still testing everything is in HTTP mode.
