### DISCUSSION TITLE
Cluster restore from file, huge performance difference between versions 14.0.7 and 14.0.19

### DISCUSSION THREAD

**Discussion by mtrejo** [infinispan/infinispan#11728] [Q&A] [answered]
Hello,

Does anyone know why would a cluster [restore](https://infinispan.org/docs/stable/titles/rest/rest.html#rest_v2_restore_cluster) take considerably longer in version 14.0.19, compared against version 14.0.7? We are restoring a ~50MB file with 2 caches, each containing around 700K entries. We are using the same configuration in both scenarios.

- xsite enabled
- persistence enabled
- 5 members, 3 owners
- distributed cache

```yaml
    distributedCache:
      mode: "SYNC"
      owners: "3"
      statistics: "true"
      partition-handling:
        merge-policy: "PREFERRED_NON_NULL"
      state-transfer:
        timeout: "360000"
        await-initial-transfer: "true"
      persistence:
        passivation: "false"
        file-store:
          shared: "false"
          data:
            path: "/opt/infinispan/server/data/store"
          index:
            path: "/opt/infinispan/server/data/index"
      backups:
        SiteGreen:
          backup:
            strategy: "ASYNC"
            stateTransfer:
              mode: "AUTO"
```

The restore takes < 20 minutes in version 14.0.7, whereas in version 14.0.19 is taking > 2 hours. We already tried disabling xsite replication and persistence, to no avail.

Thank you in advanced.
