### DISCUSSION TITLE
Unable to Deploy Infinispan Cluster on Kubernetes using Helm Chart

### DISCUSSION THREAD

**Discussion by mg-i-mat-bap** [infinispan/infinispan#12192] [Q&A] [answered]
When attempting to deploy an Infinispan cluster on Kubernetes using the provided Helm chart through ArgoCD, we encountered an error message: "Unknown desc = failed to walk for symlinks in /tmp". This issue is hindering our deployment process, and we are seeking assistance from the community in resolving it.

Application Configuration:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infinispan
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: infinispan
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
    - chart: openshift-helm-charts/infinispan-infinispan
      repoURL: https://charts.openshift.io/
      targetRevision: 0.3.2
      helm:
        valuesObject:
          images:
            server: quay.io/infinispan/server:13.0.9.Final
            initContainer: registry.access.redhat.com/ubi8-micro
          deploy:
            replicas: 2
            clusterDomain: cluster.local
            container:
              env:
                - name: USER
                  valueFrom:
                    secretKeyRef:
                      name: infinispan-credential
                      key: username
                - name: PASS
                  valueFrom:
                    secretKeyRef:
                      name: infinispan-credential
                      key: password
              storage:
                ephemeral: false
                size: 10Gi
                storageClassName: local-path
              resources:
                requests:
                  cpu: 0m
                  memory: 0Mi
                limit:
                  cpu: 500m
                  memory: 512Mi
            infinispan:
              cacheContainer:
                transport:
                  stack: "kubernetes"
                distributedCacheConfiguration:
                  name: "caching"
                  mode: "SYNC"
                  statistics: "true"
                  encoding:
                    mediaType: "application/x-jboss-marshalling"
                  expiration:
                    lifespan: "5000"
                    maxIdle: "1000"
                  memory:
                    maxCount: "1000000"
                    whenFull: "REMOVE"
            server:
              endpoints:
                - connectors:
                    rest:
                      restConnector:
                        authentication:
                          mechanisms: BASIC
                  securityRealm: metrics
                  socketBinding: metrics
            interfaces:
              - inetAddress:
                  value: ${infinispan.bind.address:infinispan.infinispan.svc.cluster.local}
                name: public
                security:
                  credentialStores:
                    - name: credentials
                      path: credentials.pfx
                      clearTextCredential:
                        clearText: secret
                    - name: metrics
                      propertiesRealm:
                        groupProperties:
                          path: metrics-groups.properties
                          relativeTo: infinispan.server.config.path
                        groupsAttribute: Roles
                        userProperties:
                          path: metrics-users.properties
                          relativeTo: infinispan.server.config.path
            socketBindings:
              defaultInterface: public
              portOffset: ${infinispan.socket.binding.port-offset:0}
              socketBinding:
                - name: default
                  port: 11222
                - name: metrics
                  port: 11223
                - name: memcached
                  port: 11221
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
```

Error Message:

```
Unknown desc = failed to walk for symlinks in /tmp
```

We have been debugging this issue for over a week without success, and we are now reaching out to the community for assistance. Any help or insights would be greatly appreciated. Thank you for your support.
