### DISCUSSION TITLE
How to use multiple resp caches with one connector?

### DISCUSSION THREAD

**Discussion by CyberLine** [infinispan/infinispan#12960] [Q&A] [answered]
regarding the following documentation:
![image](https://github.com/user-attachments/assets/ee7e5535-cbb4-4bd5-a2a5-dc08233db4af)
there should be the possibility to use `SELECT 1` and so on to switch between multiple resp caches (where default is 0)

But everything i try is resulting in the same error: 
```
127.0.0.1:6379> SELECT 1
(error) ERR DB index is out of range
```

So my question is: how should this work?

**Comment by tristantarrant** [comment]
Since the Redis `SELECT` command only supports numbers, either create caches with names `1`, `2`, etc or assign aliases with such names to other caches.

**Reply by CyberLine** [reply]
> Since the Redis `SELECT` command only supports numbers, either create caches with names `1`, `2`, etc or assign aliases with such names to other caches.

Currenty i do:
```
redis1: 
  distributedCache: 
    aliases:
      - "1"
```

its still not working as expected

**Reply by tristantarrant** [reply]
What version are you using ?

**Reply by CyberLine** [reply]
15.0.9.Final

i tested with name=1 and this works while alias=1 does not ...

**Reply by tristantarrant** [reply]
I just tried this with `15.0.9.Final` and it worked. Alias `0` points to `respCache` and alias `1` points to `a`.

![image](https://github.com/user-attachments/assets/6d717e23-2dc1-4d02-8bf8-72c5a7e44e6b)

Connecting with `redis-cli`:

![image](https://github.com/user-attachments/assets/34debbd8-edca-423d-84b1-588eb09545b5)

**Comment by karesti** [comment]
@CyberLineyou need to wait for 15.1 or use Dev version of 15.1. Here is a (yet unpublished) blog post https://github.com/infinispan/infinispan.github.io/pull/364

**Reply by CyberLine** [reply]
@karesti you are not using RESPHashFunctionPartitioner in your example. Maybe this is why its not working?

here my config:
```
redis1: 
  distributedCache: 
    configuration: "redis"
    aliases:
     - "1"
    keyPartitioner: "org.infinispan.distribution.ch.impl.RESPHashFunctionPartitioner"
    mode: "SYNC"
    remoteTimeout: "17500"
    statistics: "true"
    locking: 
      concurrencyLevel: "1000"
      acquireTimeout: "15000"
      striping: "false"
    stateTransfer: 
      timeout: "60000"
```
