### ISSUE TITLE
Configuration of DNS_PING docs didn't get ported to correct docs section

### ISSUE THREAD

**Issue by dfennessy** [infinispan/infinispan#14733]
The information for configuration of DNS_Ping should be in the correct location, specifically the information about how you should create your headless service.  

This whole section should be ported over.  

Everything in the section seems right, except we no longer use the toleration, service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
 
We now use spec.publishNotReadyAddresses: true.  

Here's an example of how to set up the spec for your headless service needed to join the pods:

```
spec: 
  type: ClusterIP 
  clusterIP: None 
  publishNotReadyAddresses: true
```
