### ISSUE TITLE
NullPointerException while expiring entry with cross-site

### ISSUE THREAD

**Issue by pruivo** [infinispan/infinispan#14865]
### Describe the bug

With async cross-site (IRAC) and max-idle:
```yaml
    replicatedCache:
      backups:
        AccA:
          backup:
            strategy: "ASYNC"
              stateTransfer:
                chunkSize: "512"
                timeout: "2400000"
                maxRetries: "30"
                waitTime: "2000"
                mode: "AUTO"
      mode: "SYNC"
      statistics: "true"
      encoding:
        key:
          mediaType: "text/plain"
        value:
          mediaType: "application/octet-stream"
      expiration:
        lifespan: "-1"
        maxIdle: "1200000"

```
The following NullPointerException is thrown:
```
java.lang.NullPointerException: Cannot invoke "org.infinispan.metadata.impl.IracMetadata.getVersion()" because "remoteMetadata" is null at 
org.infinispan.interceptors.impl.NonTxIracRemoteSiteInterceptor.validateRemoteUpdate(NonTxIracRemoteSiteInterceptor.java:153)
...
org.infinispan.xsite.ClusteredCacheBackupReceiver.removeKey(ClusteredCacheBackupReceiver.java:224) at 
org.infinispan.xsite.commands.remote.IracPutManyRequest$Expire.execute(IracPutManyRequest.java:186) at 
org.infinispan.xsite.commands.remote.IracPutManyRequest.executeOperation(IracPutManyRequest.java:61) at 
org.infinispan.xsite.commands.remote.IracUpdateKeyRequest.invokeInLocalCache(IracUpdateKeyRequest.java:24) at 
org.infinispan.xsite.commands.remote.XSiteCacheRequest.invokeInLocalSite(XSiteCacheRequest.java:55)
```

One possible cause, the IRAC queue is being flushed when a concurrent write happens. The tombstone is removed and `null` is sent with the expiration command. 
Another cause may be a concurrent tombstone cleanup while the queue is flushed. 

We should skip sending the expiration request when tombstone is `null` here:

https://github.com/infinispan/infinispan/blob/2ef455eacd651dfeff490a79e8b3210999dfc1c9/core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java#L430-L432

### Additional information

Original report: https://github.com/infinispan/infinispan-operator/discussions/2270
